ViewModels/Rewards/RewardsInputModel.cs
using System.Collections.Generic;

namespace RoyalTravel.ViewModels.Rewards
{
    public class RewardsInputModel
    {
        public RewardsInputModel()
        {
            this.StayViewModels = new List<StayViewModel>();
            this.UserDataViewModel = new UserDataViewModel();
        }
       public List<StayViewModel> StayViewModels { get; set; }

        public UserDataViewModel UserDataViewModel { get; set; }
    }
}

ViewModels/Rewards/StayViewModel.cs
using System;

namespace RoyalTravel.ViewModels
{
    public class StayViewModel
    {
        public string ConfirmationNumber { get; set; }
        public int StayId { get; set; }

        public string RoomType { get; set; }

        public decimal Price { get; set; }

        public decimal TotalPrice { get; set; }

        public DateTime ArrivalDate { get; set; }

        public DateTime DepartureDate { get; set; }

        public int? PointsEarned { get; set; }

        public int? PointsSpend { get; set; }

        public string Hotel { get; set; }

        public string Room { get; set; }

        public DateTime BookedOn { get; set; }

        public bool IsCanceled { get; set; }
    }
}

ViewModels/Rewards/UserDataViewModel.cs
namespace RoyalTravel.ViewModels.Rewards
{
    public class UserDataViewModel
    {
        public int TotalPoints { get; set; }

        public string RewardsTier { get; set; }


    }
}

Controllers/BookingController.cs
namespace RoyalTravel.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Globalization;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RoyalTravel.Data;
    using RoyalTravel.Data.Models;
    using RoyalTravel.Services.Hotel;
    using RoyalTravel.Services.Room;
    using RoyalTravel.ViewModels;
    using RoyalTravel.ViewModels.Booking;

    public class BookingController : Controller
    {
        private readonly IHotelService hotelService;
        private readonly IRoomService roomService;
        private readonly UserManager<ApplicationUser> userManager;
        public BookingController(IHotelService hotelService, IRoomService roomService, UserManager<ApplicationUser> userManager)
        {
            this.hotelService = hotelService;
            this.roomService = roomService;
            this.userManager = userManager;
        }

        public IActionResult Index(BookingViewModel viewModel)
        {
            return View(viewModel);
        }

        public async Task<IActionResult> SearchHotels([Bind]BookingInputViewModel inputModel)
        {
            if (string.IsNullOrWhiteSpace(inputModel.Destination) || inputModel.Destination.Length > 30|| inputModel.CheckOut <= inputModel.CheckIn || inputModel.CheckIn == new DateTime(0001, 01, 01) || inputModel.CheckOut == new DateTime(0001, 01, 01) || inputModel.Adults <= 0 || inputModel.Children < 0 || inputModel.Destination.Length > 30 || inputModel.CheckIn < DateTime.Today || inputModel.CheckOut < DateTime.Today)
            {
                throw new ArgumentOutOfRangeException("User Input data is incorrect! Make sure that departure date is greater than arrival date! Make sure that number of adults is not empty!");
            }

            //Check if datetime is with default value, additional checks for other parameters

            var searchedHotelsByCity = await this.hotelService.SearchWithLocationAsync(inputModel.Destination);
            var searchedHotelsByName = await this.hotelService.SearchWithHotelNameAsync(inputModel.Destination);

            var searchResultList = new List<Hotel>();
            searchResultList = searchedHotelsByCity.Count == 0 ? searchedHotelsByName : searchedHotelsByCity;
            //Searching with city is with priority and searching with name is optional

            var bookingViewModel = new BookingViewModel();
            var hotelViewModel = new List<BookingOutputViewModel>();

            foreach (var hotel in searchResultList)
            {
                var currentViewModelHotel = new BookingOutputViewModel();
                currentViewModelHotel.HotelId = hotel.Id;
                currentViewModelHotel.HotelName = hotel.Name;
                currentViewModelHotel.Address = hotel.Address.Street
                 + ", " + hotel.Address.City + ", " + hotel.Address.State + ", " + hotel.Address.PostalCode;
                currentViewModelHotel.PetFriendly = hotel.Amenity.AllowPets == true ? "Yes" : "No";
                currentViewModelHotel.Wifi = hotel.Amenity.WiFi == true ? "Yes" : "No";
                currentViewModelHotel.Pool = hotel.Amenity.Pool == true ? "Yes" : "No";
                currentViewModelHotel.Stars = hotel.Stars;
                currentViewModelHotel.Image = hotel.Image;
                
                hotelViewModel.Add(currentViewModelHotel);
            }
            bookingViewModel.BookingOutputViewModels = hotelViewModel;
            //Contains information about the searched hotels;
            bookingViewModel.InputModel = inputModel;
            //Contains information about the input, including validation

            //TODO Implement Paging 

            return this.View("Index", bookingViewModel);

        }

        public async Task<IActionResult> SelectHotel(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound("Hotel not found!");
            }

            var hotelQuery = await this.hotelService.FindHotelById(id);
            var hotel = hotelQuery.FirstOrDefault();

            var hotelViewModel = new SelectedHotelViewModel()
            {
                HotelName = hotel.Name,
                Address = hotel.Address.Street
                 + ", " + hotel.Address.City + ", " + hotel.Address.State + ", " + hotel.Address.PostalCode,
                AirportShuttle = hotel.Amenity.AirportShuttle,
                AllowPets = hotel.Amenity.AllowPets,
                Breakfast = hotel.Amenity.Breakfast,
                FitnessCenter = hotel.Amenity.Fitness,
                LocalShuttle = hotel.Amenity.LocalShuttle,
                Parking = hotel.Amenity.Parking,
                Pool = hotel.Amenity.Pool,
                WiFi = hotel.Amenity.WiFi,
                Restaurant = hotel.Amenity.Restaurant,
                Description = hotel.Info.PropertyDescription,
                Information = hotel.Info.AreaInfo + Environment.NewLine + hotel.Info.AmenitiesInfo,
                CheckInTime = hotel.Info.CheckIn,
                CheckOutTime = hotel.Info.CheckOut,
                MinCheckInAge = hotel.Info.CheckIn,
                LocationLink = hotel.LocationLink,
                Policies = hotel.Info.Policies,
                RoomTypes = hotel.Rooms
                    .GroupBy(r => new { r.RoomType, r.Price, r.Smoking })
                    .Select(g => g.First()),
            };

            return this.View(hotelViewModel);
        }


        public async Task<IActionResult> BookHotel(int? id, string checkIn, string checkOut, int adults, int children)
        {
            try
            {
                var checkInDateTemp = DateTime.ParseExact(checkIn, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                var checkOutDateTemp = DateTime.ParseExact(checkOut, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            }
            catch (Exception)
            {
                throw new ArgumentOutOfRangeException("Invalid dates!");
            }

            // Validate the dates parsing if the user modified the URL
            var checkInDate = DateTime.ParseExact(checkIn, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            var checkOutDate = DateTime.ParseExact(checkOut, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            int nightsStay = (checkOutDate - checkInDate).Days;

            if (checkOutDate <= checkInDate || id == null || adults == 0 || checkInDate == checkOutDate || checkInDate == null || checkOutDate == null)
            {
                throw new ArgumentOutOfRangeException("Invalid input data! Check out date should be after the check in date! Minimum number of adults is one! Hotel indentifier is required!");
                //Additional validation for all required parameters
            }

            var hotelQuery = await hotelService.FindHotelById(id);
            var selectedHotel = hotelQuery.FirstOrDefault();

            var bookHotelViewModel = new MakeBookingViewModel()
            {
                HotelId = selectedHotel.Id,
                HotelName = selectedHotel.Name,
                CheckIn = checkIn,
                CheckOut = checkOut,
                Adults = adults,
                Children = children,
                NumberOfNights = nightsStay,
                RoomsGroup = selectedHotel.Rooms
                    .GroupBy(r => new { r.RoomType, r.Price, r.Smoking })
                    .Select(g => g.First()),

                // Sorting and grouping the rooms to filter all rooms by room type, price and if they are smoking or non smoking
                RoomsAvailability = selectedHotel.Rooms
                    .Where(room => room.Stays.All(res => res.DepartureDate <= checkInDate || res.ArrivalDate >= checkOutDate)),

                // Gets all the rooms which are available
            };


            return this.View(bookHotelViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Confirm(int? id, string checkIn, string checkOut, int adults, int children, string roomType)
        {
            var checkInDate = DateTime.ParseExact(checkIn, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            var checkOutDate = DateTime.ParseExact(checkOut, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            var selectedHotel = this.hotelService.FindSingleHotelById(id).Result;

            // Will get first available room by given type
            var selectedAvailableRoom = selectedHotel.Rooms
                .Where(room => room.Stays.All(res => res.DepartureDate <= checkInDate || res.ArrivalDate >= checkOutDate))
                .FirstOrDefault(r => r.RoomType == roomType);

            // Additional validation for all required parameters
            if (checkOutDate <= checkInDate || adults < 1 || id == null ||
                selectedAvailableRoom.MaxOccupancy < adults + children)
            {
                throw new ArgumentOutOfRangeException("Error: Invalid input data!");
            }

            var reservation = new Stay
            {
                RoomType = roomType,
                ArrivalDate = checkInDate,
                DepartureDate = checkOutDate,
                Price = selectedAvailableRoom.Price,
                TotalPrice = selectedAvailableRoom.Price * (checkOutDate - checkInDate).Days,
                HotelId = (int)id,
                RoomId = selectedAvailableRoom.Id,
                MoneySpend = selectedAvailableRoom.Price * (checkOutDate - checkInDate).Days,
                ApplicationUserId = this.userManager.GetUserId(User),
                ConfirmationNumber = this.roomService.GenerateConfirmationNumber(selectedHotel.Name),
                Adults = adults,
                Children = children,
                BookedOn = DateTime.Now,
                IsCanceled = false,

Controllers/RewardsController.cs
namespace RoyalTravel.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Logging;
    using RoyalTravel.Data;
    using RoyalTravel.Data.Models;
    using RoyalTravel.Services.Stays;
    using RoyalTravel.Services.User;
    using RoyalTravel.ViewModels;
    using RoyalTravel.ViewModels.Rewards;

    [Authorize]
    public class RewardsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IStaysService staysService;

        public RewardsController(UserManager<ApplicationUser> userManager, IUserService userService, IStaysService staysService)
        {
            this.userManager = userManager;
            this.staysService = staysService;
        }

        public IActionResult Index()
        {
            var currentUser = this.userManager.GetUserAsync(this.User).Result;
            var rewardsViewModel = new RewardsInputModel();
            var stays = this.staysService.GetAllStaysForUser(currentUser.Id);

            // Gets all stays for the user including the data for the hotxel and sorted by date of booking

            int totalPoints = this.staysService.GetTotalPoints(currentUser.Id);

            // Gets total points of all stays, which are not canceled. User will get points only if departure date is 
            // less or equal to today's date
            int pointsRefunded = this.staysService.GetRefundedPoints(currentUser.Id);

            // Gets total points for canceled reservation and refund it to the user so he can use them again
            var userTier = string.Empty;

            if (totalPoints <= StaticData.RewardsTier1Requirement)
            {
                userTier = StaticData.Tiers.Silver.ToString();
            }
            else if (totalPoints >= StaticData.RewardsTier2Requirement)
            {
                userTier = StaticData.Tiers.Gold.ToString();
            }
            else if (totalPoints >= StaticData.RewardsTier3Requirement)
            {
                userTier = StaticData.Tiers.Platinum.ToString();
            }

            // Get the user tier acording to total points earned
            totalPoints = totalPoints - currentUser.UsedPoints + pointsRefunded;
            // Gets the remaining points for the user
            rewardsViewModel.UserDataViewModel.TotalPoints = totalPoints;
            rewardsViewModel.UserDataViewModel.RewardsTier = userTier;

            foreach (var stay in stays)
            {
                var stayViewModel = new StayViewModel()
                {
                    ConfirmationNumber = stay.ConfirmationNumber,
                    Hotel = stay.Hotel.Name,
                    RoomType = stay.RoomType,
                    ArrivalDate = stay.ArrivalDate,
                    DepartureDate = stay.DepartureDate,
                    PointsSpend = stay.PointsSpend,
                    PointsEarned = stay.PointsEarned,
                    Price = stay.Price,
                    TotalPrice = stay.TotalPrice,
                    StayId = stay.Id,
                    IsCanceled = stay.IsCanceled,
                    BookedOn = stay.BookedOn,
                };
                rewardsViewModel.StayViewModels.Add(stayViewModel);
            }

            return this.View(rewardsViewModel);
        }

        public async Task<IActionResult> CancelReservation(int stayId)
        {
            if (stayId == 0)
            {
                return this.NotFound("Reservation not found!");
            }

            this.staysService.CancelReservation(stayId);

            // Will mark the reservation as canceled
            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> UsePoints(int stayId)
        {
            var currentUser = await userManager.GetUserAsync(User);
            var selectedStay = staysService.FindStayById(stayId);
            if (stayId == 0)
            {
                return NotFound("Reservation not found!");
            }
            if (selectedStay.TotalPrice < selectedStay.Price)
            {
                throw new InvalidOperationException("Invalid points usage!");
            }
            currentUser.UsedPoints += StaticData.FreeNightPoints;
            //Add the default points per night value to the user
            staysService.UsePoints(stayId);

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> About()
        {
            return this.View("About");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Rewards/About.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="/Images/carousel2.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/carousel1.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/carousel3.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Rewards/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using RoyalTravel.Data.Models

@inject UserManager<ApplicationUser> userManager
@model RoyalTravel.ViewModels.Rewards.RewardsInputModel

@{
    ViewData["Title"] = "Royal Rewards";
}
<head>
</head>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="main">
                <div id="page-content-wrapper">
                    @if (Model.StayViewModels.Count == 0)
                    {
                        <div class="alert alert-dark text-center" role="alert">
                            You don't have any reservations yet! You can find some accommodations <a class="alert-link" asp-controller="Booking" asp-action="Index">here</a>.
                        </div>
                    }
                    else
                    {
                        <div class="col-md-3 text-center">
                            Total Points Earned: @Model.UserDataViewModel.TotalPoints
                        </div>
                        <div class="col-md-3 text-center">
                            Current Tier: @Model.UserDataViewModel.RewardsTier
                        </div>
                        <div class="col-md-3 text-center row">
                            <a type="submit" class="btn btn-success btn-sm" asp-controller="Rewards" asp-action="About">
                                About Rewards Program
                            </a>
                        </div>
                        <table class="table table-striped text-center">

                            <thead>
                                <tr>
                                    <th scope="col">Booked On</th>
                                    <th scope="col">Hotel Name</th>
                                    <th scope="col">Room type</th>
                                    <th scope="col">Arrival</th>
                                    <th scope="col">Departure</th>
                                    <th scope="col">Points to Earn</th>
                                    <th scope="col">Points Spend</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Total Price</th>
                                    <th scope="col"></th>
                                    <th scope="col">Use Points</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var stay in Model.StayViewModels)
                                {
                                    <tr>
                                        <td>@stay.BookedOn</td>
                                        <td>@stay.Hotel</td>
                                        <td>@stay.RoomType</td>
                                        <td>@stay.ArrivalDate.ToString("MM/dd/yyyy")</td>
                                        <td>@stay.DepartureDate.ToString("MM/dd/yyyy")</td>
                                        <td>@stay.PointsEarned</td>
                                        <td>
                                            @if (stay.PointsSpend == null)
                                            {
                                                <p>0</p>
                                            }
                                            else
                                            {
                                                <span class="text-success">@stay.PointsSpend</span>
                                            }
                                        </td>
                                        <td>@stay.Price$</td>
                                        <td>@stay.TotalPrice$</td>
                                        <td>
                                            @if (stay.DepartureDate == DateTime.Today)
                                            {

                                            }
                                            else
                                            {
                                                if (stay.ArrivalDate <= DateTime.Today)
                                                {
                                                    <button type="button" class="btn btn-warning btn-sm">
                                                        Past reservation
                                                    </button>
                                                }
                                                else
                                                {
                                                    if (stay.IsCanceled)
                                                    {
                                                        <button type="button" class="btn btn-dark btn-sm">
                                                            Canceled
                                                        </button>
                                                    }
                                                    else
                                                    {
                                                        <form method="get">
                                                            <a type="submit" class="btn btn-danger btn-sm" asp-controller="Rewards" asp-action="CancelReservation" asp-route-stayId="@stay.StayId">
                                                                Cancel<span class="ml-1"><i class="fas fa-times"></i></span>
                                                            </a>
                                                        </form>

                                                    }

                                                }

                                            }
                                        </td>
                                        <td>
                                            @if (Model.UserDataViewModel.TotalPoints >= 15000 && stay.IsCanceled == false && stay.DepartureDate > DateTime.Today && stay.TotalPrice >= stay.Price)
                                            {
                                                <form method="get">
                                                    <a type="submit" class="btn btn-success btn-sm" asp-controller="Rewards" asp-action="UsePoints" asp-route-stayId="@stay.StayId">
                                                        15,000 Points 
                                                    </a>

                                                </form>
                                            }

                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    }

                </div>
            </div>
        </div>
    </div>
</div>


@*<form method="get" asp-controller="Booking" asp-action="SearchHotels">
        <div class="row">
            <div class="col">
                <label for="destination">Where to?</label>
                <input asp-for="InputModel.Destination" class="form-control" type="text" id="destination" width="276" name="destination" placeholder="Enter Destination" required />
            </div>
            <div class="col">
                <label for="dp1">Arrival</label>
                <input id="dp1" type="text" class="form-control clickable input-md" id="DtChkIn" placeholder="&#xf133;  Check-In" width="276" name="checkIn" required autocomplete="off">
            </div>
            <div class="col">
                <label for="dp2">Departure</label>
                <input id="dp2" type="text" class="form-control clickable input-md" id="DtChkOut" placeholder="&#xf133;  Check-Out" width="276" name="checkOut" required autocomplete="off">
            </div>
            <div class="col">
                <label for="adults">Adults</label>
                <select asp-for="InputModel.Adults" class="form-control" id="adults" width="276" name="adults" required>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                </select>
            </div>
            <div class="col">
                <label for="kids">Children</label>
                <select class="form-control" id="kids" width="276" name="children">
                    <option>0</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
        </div>
        <div style="margin-top:24px" class="row">
            <button type="submit" class="btn btn-primary btn-lg btn-block" asp-controller="Booking" asp-action="SearchHotels">Find Hotels</button>
        </div>
    </form>*@

<script src="~/js/JsQuery/jquery.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>