Areas/Administration/ViewModels/AllUsersViewModel.cs
namespace RoyalTravel.Areas.Administration.ViewModels
{
    public class AllUsersViewModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string EmailAddress { get; set; }

        public string UsedPoints { get; set; }

        public string EmailIsConfirmed { get; set; }
    }
}

Areas/Administration/ViewModels/EarningsViewModel.cs
namespace RoyalTravel.Areas.Administration.ViewModels
{
    public class EarningsViewModel
    {
        public string TotalEarnings { get; set; }

        public string Commission { get; set; }

        public string EarningsAfterTaxAndCommission { get; set; }

        public int TotalReservations { get; set; }
    }
}

Areas/Administration/ViewModels/ReservationViewModel.cs
using System;

namespace RoyalTravel.Areas.Administration.ViewModels
{
    public class ReservationsViewModel
    {
        public string RoomType { get; set; }

        public string MoneySpend { get; set; }

        public string ArrivalDate { get; set; }
        public DateTime Darrival {  get; set; }

        public string DepartureDate { get; set; }
        
        public DateTime Ddeparture { get; set; }

        public bool IsCanceled { get; set; }
        public string PricePerNight { get; set; }

        public string TotalPrice { get; set; }

        public string PointsEarned { get; set; }

        public string HotelName { get; set; }

        public string UserName { get; set; }

        public string ConfirmationNumber { get; set; }

        public string Adults { get; set; }

        public string Children { get; set; }

        public DateTime BookedOn { get; set; }

        public int StayId { get; set; }

    }
}

Areas/Administration/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RoyalTravel.Areas.Administration.ViewModels;
using RoyalTravel.Data;
using RoyalTravel.Data.Models;
using RoyalTravel.Services.Hotel;
using RoyalTravel.Services.Stays;
using RoyalTravel.Services.User;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoyalTravel.Areas.Administration.Controllers
{
    [Area(nameof(Administration))]
    [Route("/[controller]/[action]")]
    [Authorize(Policy = "RequireAdmin")]
    public class AdministrationController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IUserService userService;
        private readonly IStaysService staysService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IHotelService hotelService;

        public AdministrationController(ApplicationDbContext dbContext, IUserService userService, IStaysService staysService, UserManager<ApplicationUser> userManager, IHotelService hotelService)
        {
            
            db = dbContext;
            this.userService = userService;
            this.staysService = staysService;
            this.userManager = userManager;
            this.hotelService = hotelService;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AllUsers()
        {
            var users = db.Users.ToList();
            var usersViewModel = new List<AllUsersViewModel>();

            foreach (var user in users)
            {
                var currentUser = user;
                if (user.Email == "yokhawand@gmail.com") { }
                else
                {
                    usersViewModel.Add(new AllUsersViewModel
                    {
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        EmailAddress = user.Email,
                        EmailIsConfirmed = user.EmailConfirmed ? "Yes" : "No",
                        UsedPoints = user.UsedPoints.ToString(),
                    });
                }

            }
            return View(usersViewModel);
        }

        public IActionResult CancelRes(int stayId)
        {
            if (stayId == 0)
            {
                return PartialView("_NoDataPartial");
            }
            var stay = db.Stays.First(s => s.Id == stayId);
            stay.IsCanceled = true;
            db.Stays.Remove(stay);
            db.SaveChanges();
            return RedirectToAction("AllReservations");

           
        }

        public IActionResult AllReservations()
        {
            var allReservations = staysService.AllReservations();
            if (allReservations == null || allReservations.Count <= 0)
            {
                return PartialView("_NoDataPartial");
            }
            var reservationsViewModel = new List<ReservationsViewModel>();

            foreach (var stay in allReservations)
            {
                var viewModel = new ReservationsViewModel
                {
                    RoomType = stay.RoomType,
                    MoneySpend = stay.MoneySpend.ToString(),
                    ArrivalDate = stay.ArrivalDate.ToString("MM/dd/yyyy"),
                    DepartureDate = stay.DepartureDate.ToString("MM/dd/yyyy"),
                    Darrival = stay.ArrivalDate,
                    Ddeparture = stay.DepartureDate,
                    PricePerNight = stay.Price.ToString(),
                    TotalPrice = stay.TotalPrice.ToString(),
                    PointsEarned = stay.PointsEarned.ToString(),
                    HotelName = hotelService.FindSingleHotelById(stay.HotelId).Result.Name,
                    UserName = userService.GetUser(stay.ApplicationUserId).UserName,
                    Adults = stay.Adults.ToString(),
                    Children = stay.Children.ToString(),
                    ConfirmationNumber = stay.ConfirmationNumber,
                    BookedOn = stay.BookedOn,
                    StayId = stay.Id
                };
                reservationsViewModel.Add(viewModel);
            }
            return View(reservationsViewModel);
        }

    }
   

}

Areas/Administration/Views/Administration/AllReservations.cshtml
@model List<RoyalTravel.Areas.Administration.ViewModels.ReservationsViewModel>
@{
    ViewData["Title"] = "AllReservations";
}

<div class="row">
    <table class="table table-borderless">
        <thead class="text-center">
            <tr>
                <th scope="col">Confirmation Number</th>
                <th scope="col">Booked On</th>
                <th scope="col">Money Spend</th>
                <th scope="col">Arrival Date</th>
                <th scope="col">Departure Date</th>
                <th scope="col">Price/night</th>
                <th scope="col">Total Price</th>
                <th scope="col">Points Earned</th>
                <th scope="col">Hotel Name</th>
                <th scope="col">Username</th>
                <th scope="col">Adults</th>
                <th scope="col">Children</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var res in Model)
            {
                <tr class="text-center">
                    <td>@res.ConfirmationNumber</td>
                    <td>@res.BookedOn</td>
                    <td>@res.MoneySpend</td>
                    <td>@res.ArrivalDate</td>
                    <td>@res.DepartureDate</td>
                    <td>@res.PricePerNight</td>
                    <td>@res.TotalPrice</td>
                    <td>@res.PointsEarned</td>
                    <td>@res.HotelName</td>
                    <td>@res.UserName</td>
                    <td>@res.Adults</td>
                    <td>@res.Children</td>
                    <td>
                        @if (@res.Darrival <= res.BookedOn)
                        {
                            
                        }
                        else
                        {
                           <form method="get">
                                <a type="submit" class="btn btn-danger btn-sm" asp-controller="Administration" asp-action="CancelRes"
                             asp-route-stayId="@res.StayId">Cancel<span class="ml-1"><i class="fas fa-times"></i></span>
                            </a>
                        </form> 
                        }
                    </td>
            </tr>
           
            }
        </tbody>
    </table>
    <a class="text-center btn btn-outline-danger" href="##" onClick="history.go(-1); return false;"> Go Back</a>
</div>

Areas/Administration/Views/Administration/AllUsers.cshtml
@model List<RoyalTravel.Areas.Administration.ViewModels.AllUsersViewModel>
@{
    ViewData["Title"] = "AllUsers";
}

<div class="row">
    <table class="table table-borderless text-center">
        <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email Address</th>
                <th scope="col">Confirmed Email</th>
                <th scope="col">Total Points Used</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <th>@user.FirstName</th>
                    <td>@user.LastName</td>
                    <td>@user.EmailAddress</td>
                    <td>@user.EmailIsConfirmed</td>
                    <td>@user.UsedPoints</td>
                </tr>

            }
        </tbody>
    </table>
    <a class="text-center btn btn-outline-danger" href="##" onClick="history.go(-1); return false;"> Go Back</a>
</div>

Areas/Administration/Views/Administration/Earnings.cshtml
@model RoyalTravel.Areas.Administration.ViewModels.EarningsViewModel

@{
    ViewData["Title"] = "Earnings";
}

<div class="row">
    <table class="table table-borderless">
        <thead class="text-center">
            <tr>
                <th scope="col">Total Paid Reservations</th>
                <th scope="col">Total Earnings</th>
                <th scope="col">Royal Travel Commission</th>
                <th scope="col">Earnings Commission</th>
            </tr>
        </thead>
        <tbody>
            <tr class="text-center">
                <th>@Model.TotalReservations</th>
                <td>@Model.TotalEarnings $</td>
                <td>@Model.Commission%</td>
                <td>@Model.EarningsAfterTaxAndCommission $</td>
            </tr>
        </tbody>
    </table>
    <a class="text-center btn btn-outline-danger" href="##" onClick="history.go(-1); return false;"> Go Back</a>
</div>

Areas/Administration/Views/Administration/Index.cshtml
<h1 class="text-center">Welcome, Admin!</h1>

<div class="row text-center">
    <div class="col-md-4">
        <a class="btn btn-outline-danger btn-lg" asp-area="Administration" asp-controller="Administration" asp-action="AllUsers">Get All Users Stats</a>
    </div>
    <div class="col-md-4">
        <a class="btn btn-outline-danger btn-lg" asp-area="Administration" asp-controller="Administration" asp-action="Earnings">View Earnings & Commission Stats</a>
    </div>
    <div class="col-md-4">
        <a class="btn btn-outline-danger btn-lg" asp-area="Administration" asp-controller="Administration" asp-action="AllReservations">All Reservations</a>
    </div>
</div>